#!/bin/sh
#
# FiloSottile/age wrapper that makes it easier
# to encrypt files for GitHub users.
#
# Usage: gage <github-user> <file>
#
gh_user="$1"
file="$2"
if [ -z "$gh_user" ]; then
  echo "Usage: gage <github-user> <file>" >&2
  exit 1
fi

key=$(curl -s https://github.com/$gh_user.keys|tail -n1)
if [ -z "$key" ] || expr "$key" : "Not.Found" >/dev/null; then
  echo "Use key for $gh_user not found." >&2
  exit 1
fi
keyid=$(echo $key | grep -o '......$')

# Encrypt and send the ciphertext.age to @ptoomey3
echo "** Encrypting for $gh_user with key '$keyid'..."
age -o "$file.age" -r "$key" "$file"
echo "** File encrypted: $file.age"
