#!/bin/sh
#
# FiloSottile/age wrapper that makes it easier
# to encrypt files for GitHub users.
#
# Usage: gage <github-user> <file>
#
set -e

users="$1"
file="$2"
if [ -z "$users" ]; then
  echo "Usage: gage <github-user> <file>" >&2
  exit 1
fi

recipients=""
for user in $(echo $users | sed "s/,/ /g"); do
  key=$(curl -s https://github.com/$user.keys | tail -n1)
  if [ -z "$key" ] || expr "$key" : "Not.Found" >/dev/null; then
    echo "Use key for $user not found." >&2
    exit 1
  fi
  recipients="$recipients -r '$key'"
done
echo "** Encrypting for users $users..."
echo age "$recipients" -o "$file.age" "$file" | sh
echo "** File encrypted: $file.age"
