#!/bin/sh
#
# FiloSottile/age wrapper that makes it easier
# to encrypt files for GitHub users.
#
# Usage: gage <github-user> <file>
#
gh_user="$1"
file="$2"
if [ -z "$gh_user" ]; then
  echo "Usage: gage <github-user> <file>" >&2
  exit 1
fi

KEY=$(curl -s https://github.com/$gh_user.keys)
if [ -z "$KEY" ] || expr "$KEY" : "Not.Found" >/dev/null; then
  echo "Use key for $gh_user not found." >&2
  exit 1
fi

# Encrypt and send the ciphertext.age to @ptoomey3
age -o "$file.age" -r "$KEY" "$file"
echo "$file.age encrypted."
