#!/bin/sh
set -e

version="$1"
if [ -z "$version" ]; then
  echo "Invalid go version" >&2
  exit 1
fi

if ! curl -q -f -I -L https://golang.org/dl/go$version.linux-amd64.tar.gz >/dev/null 2>&1; then
  echo "Error downloading Go version $version" >&1
  exit 1
fi

sudo rm -rf /usr/local/go
echo "Donwloading go version $version..."
curl -s --output - -L https://golang.org/dl/go$version.linux-amd64.tar.gz | sudo tar -C /usr/local -xzvf - >/dev/null
